// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALLGR9Yzp_J-p2Y8hj74TZUCPgJWHp2GQ',
    appId: '1:373253484293:android:c2c3d60d175b8a68ec916c',
    messagingSenderId: '373253484293',
    projectId: 'cvdriskanalysis-4cc3d',
    storageBucket: 'cvdriskanalysis-4cc3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjEP4VUgtbLb0uSWk9qCFnEj_URDdUD-Q',
    appId: '1:373253484293:ios:86c867cf535c7889ec916c',
    messagingSenderId: '373253484293',
    projectId: 'cvdriskanalysis-4cc3d',
    storageBucket: 'cvdriskanalysis-4cc3d.appspot.com',
    iosBundleId: 'com.example.cvdRiskAnalyser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjEP4VUgtbLb0uSWk9qCFnEj_URDdUD-Q',
    appId: '1:373253484293:ios:d60a57251230e623ec916c',
    messagingSenderId: '373253484293',
    projectId: 'cvdriskanalysis-4cc3d',
    storageBucket: 'cvdriskanalysis-4cc3d.appspot.com',
    iosBundleId: 'com.example.cvdRiskAnalyser.RunnerTests',
  );
}
